insert into rooms_room (type_room, price) values ('Deluxe', 226.67);
insert into rooms_room (type_room, price) values ('Double', 274.15);
insert into rooms_room (type_room, price) values ('Twin', 285.66);
insert into rooms_room (type_room, price) values ('Single', 375.59);
insert into rooms_room (type_room, price) values ('Single', 691.05);
insert into rooms_room (type_room, price) values ('Twin', 324.91);
insert into rooms_room (type_room, price) values ('Deluxe', 221.81);
insert into rooms_room (type_room, price) values ('Double', 127.08);
insert into rooms_room (type_room, price) values ('Double', 187.17);
insert into rooms_room (type_room, price) values ( 'Double', 272.66);
insert into rooms_room (type_room, price) values ( 'Double', 737.52);
insert into rooms_room (type_room, price) values ( 'Double', 375.97);
insert into rooms_room (type_room, price) values ( 'Single', 310.52);
insert into rooms_room (type_room, price) values ( 'Double', 264.78);
insert into rooms_room (type_room, price) values ( 'Double', 964.06);
insert into rooms_room (type_room, price) values ( 'Deluxe', 113.97);
insert into rooms_room (type_room, price) values ( 'Twin', 314.21);
insert into rooms_room (type_room, price) values ( 'Twin', 346.84);
insert into rooms_room (type_room, price) values ( 'Double', 151.71);
insert into rooms_room (type_room, price) values ( 'Twin', 280.54);
insert into rooms_room (type_room, price) values ( 'Twin', 314.63);
insert into rooms_room (type_room, price) values ( 'Single', 396.03);
insert into rooms_room (type_room, price) values ( 'Double', 109.79);
insert into rooms_room (type_room, price) values ( 'Deluxe', 395.2);
insert into rooms_room (type_room, price) values ( 'Single', 364.86);
